### PR TITLE
Update .yml => .yaml

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Review by odolbeau — APPROVED** [review]

**Review by bocharsky-bw — APPROVED** [review]
Thank you 👍

**Comment by Nyholm** [comment]
Thank you for merging

**Comment by bocharsky-bw** [comment]
@Nyholm IIRC it should be deployed automatically? I don't see yet that changes were applied on https://php-translation.readthedocs.io/

**Comment by Nyholm** [comment]
I had to reauthenticate the github - readhedocs integration. It should build automatically now.

**Comment by bocharsky-bw** [comment]
Thanks! I see these changes were applied on the website 👍

**Pull request merged**
