### PR TITLE
Add doc for symfony-bundle application delivery

### PR DESCRIPTION
**Pull request by sterrien**
Documentation for this feature : https://github.com/php-translation/symfony-bundle/pull/256

### CODE REVIEW

**Review by Nyholm — CHANGES_REQUESTED** [review]
Awesome. Thank you

**Review by Nyholm — APPROVED** [review]
(Wron button)

**Comment by Nyholm** [comment]
(And typos) :)

Thanks

**Comment by sterrien** [comment]
You're welcome !

**Pull request merged**
