### PR TITLE
Update configure-httplug.rst

### PR DESCRIPTION
**Pull request by B-Galati**
Remove disable SSL certificate check

### CODE REVIEW

**Comment by Nyholm** [comment]
I do agree that nobody should use `verify: false`. But that is the number one issue people (especially on Windows) as for. 

Could you make a comment that says something like "This should always be true in production". Also, maybe change it to `verify: true`?

**Comment by B-Galati** [comment]
@Nyholm Done something, not exactly what you proposed. Let me know if it's ok for you or not.

**Comment by B-Galati** [comment]
I don't get why the CI is failing ^^'

**Comment by Nyholm** [comment]
I restarted the CI and it works. Thank you

**Pull request merged**
